import Head from "next/head";
import { FC } from "react";

const HeadComponent: FC = () => (
  <>
    <Head>
      <title>CogBlog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
    </Head>
  </>
);

export default HeadComponent;